# Generated by Django 5.1.3 on 2024-12-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Birth year"),
        ),
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.IntegerField(blank=True, null=True, verbose_name="Pages"),
        ),
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Year"),
        ),
        migrations.AddField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.genre",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
